export const AuthApplicationErrorCode = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  INVALID_OR_EXPIRED_TOKEN: 'INVALID_OR_EXPIRED_TOKEN',
  PROVIDER_ALREADY_LINKED: 'PROVIDER_ALREADY_LINKED',
  PROVIDER_NOT_LINKED: 'PROVIDER_NOT_LINKED',
  PASSWORD_ALREADY_SET: 'PASSWORD_ALREADY_SET',
} as const

export type AuthApplicationErrorCode = typeof AuthApplicationErrorCode[keyof typeof AuthApplicationErrorCode];