export const UserErrorCode = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_USER_NAME: 'USER_INVALID_NAME',
  INVALID_PHONE_NUMBER: 'USER_INVALID_PHONE_NUMBER',
  INVALID_AVATAR_URL: 'USER_INVALID_AVATAR_URL',
  INVALID_ADDRESS: 'USER_INVALID_ADDRESS',
  ADDRESS_NOT_FOUND: 'USER_ADDRESS_NOT_FOUND',
} as const;

export type UserErrorCode = typeof UserErrorCode[keyof typeof UserErrorCode];
